DATASET:
  TRAIN: "/content/drive/MyDrive/Synt data test/fastestdet/train.txt"
  VAL: "/content/drive/MyDrive/Synt data test/fastestdet/val.txt"
  NAMES: "/content/drive/MyDrive/Synt data test/fastestdet/category.names"
MODEL:
  NC: 2
  INPUT_WIDTH: 1024
  INPUT_HEIGHT: 72
TRAIN:
  LR: 0.001
  THRESH: 0.25
  WARMUP: true
  BATCH_SIZE: 96
  END_EPOCH: 300
  MILESTIONES:
    - 100
    - 200
    - 250